# 開発用Dockerfile
# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.2

# 基本的なパッケージをインストールしキャッシュは削除
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base
WORKDIR /myapp
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl \
    libjemalloc2 \
    libvips \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# baseを元にgemをインストールしキャッシュは削除
FROM base AS build
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential \
    git \
    libpq-dev \
    libyaml-dev \
    pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
# 開発環境なので全てのgemをインストール
ENV RAILS_ENV="development" \
#   BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle"
#   BUNDLE_WITHOUT="development"
# gemfileをコピーしてからインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache
# Copy application code
COPY . .
# プリコンパイルを実施
# frontステージからビルド済みCSSをコピーして一緒にプリコンパイルする
#COPY --from=front /myapp/app/assets/builds/ ./app/assets/builds/
# Precompile bootsnap code for faster boot times
#RUN bundle exec bootsnap precompile app/ lib/
# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
#RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile


# 開発環境；生成した内容をコピーしてビルド
FROM build AS development
# 本番環境
ENV RAILS_ENV="development" \
#   BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle"
#   BUNDLE_WITHOUT="development"
# 生成したgemとアプリ用のファイルをコピー
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /myapp /rails
# Run and own only the runtime files as a non-root user for security
#RUN groupadd --system --gid 1000 rails && \
#   useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
#   chown -R rails:rails db log storage tmp
#USER 1000:1000
# Entrypoint prepares the database.
#ENTRYPOINT ["/rails/bin/docker-entrypoint"]
# ポートは変数で指定 サーバー起動はProcfileで指定するため省略
EXPOSE 3000
#CMD ["./bin/dev"]
CMD ["./bin/dev"]